### ISSUE TITLE
curl problem with ssl together with netCDF

### ISSUE THREAD

**Issue by ReimarBauer** [conda-forge/netcdf4-feedstock#16]
Only on an ssl connection to my server I see these lines

```
[Fri Jul 08 16:42:32.658871 2016] [wsgi:error] [pid 20343:tid 140526487525120] [client ]     import netCDF4
[Fri Jul 08 16:42:32.658888 2016] [wsgi:error] [pid 20343:tid 140526487525120] [client ]   File "/home/user/miniconda2/lib/python2.7/site-packages/netCDF4/__init__.py", line 3, in <module>
[Fri Jul 08 16:42:32.658915 2016] [wsgi:error] [pid 20343:tid 140526487525120] [client ]     from ._netCDF4 import *
[Fri Jul 08 16:42:32.658955 2016] [wsgi:error] [pid 20343:tid 140526487525120] [client ] ImportError: /home/user/miniconda2/lib/python2.7/site-packages/netCDF4/../../.././libcurl.so.4: undefined symbol: SSLv2_client_method
[Fri Jul 08 16:42:32.660183 2016] [ssl:debug] [pid 20343:tid 140526487525120] ssl_engine_io.c(1016): [client] AH02001: Connection closed 
```

Current conda install:

```
              platform : linux-64
        conda version : 4.1.6
    conda-env version : 2.5.1
  conda-build version : 1.21.5
       python version : 2.7.12.final.0
     requests version : 2.10.0
     root environment : /home/user/miniconda2  (writable)
  default environment : /home/user/miniconda2
     envs directories : /home/user/miniconda2/envs
        package cache : /home/user/miniconda2/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /home/user/.condarc
         offline mode : False
    is foreign system : False
```

If I verify SSLv2_client_method symbols in current curl version, they seem to be there. 
But it did give the same error,

An old 7.26 curl works.  Have you an idea what the cause could be?

**Comment by ocefpaf** [comment]
Thanks for the report @ReimarBauer. I believe this is related to https://github.com/conda-forge/openssl-feedstock/issues/2

Note that `netCDF4` depends on `libetcdf` and the `OPeNDAP` support depends on `curl`. conda-forge's `curl` is compiled against `openssl` (see https://github.com/conda-forge/curl-feedstock/blob/master/recipe/meta.yaml#L27).

So ultimately this is not a netCDF4 issues but let's leave this issue open until we address it properly in `openssl`.

**Comment by jakirkham** [comment]
I have pulled the `ca-certificates` build that caused this problem.

There was a change in the environment variable used to specify the active conda environment, which caused this to break. We are working on a fix to navigate these differences in conda, but are running into some Windows build issues that are blocking progress.

To restore to a working version of `ca-certificates` in an existing environment, try this `conda install -c conda-forge ca-certificates=2016.2.28=0`.

**Comment by ocefpaf** [comment]
@ReimarBauer I believe the issue was addressed. If that returns let me know.

**Comment by ReimarBauer** [comment]
Tried this again, only intalling ca-certificates=2016.2.28=0 does not fix it.

**Comment by jakirkham** [comment]
I'm not sure that workaround still applies. Are you using a fresh environment?

**Comment by ReimarBauer** [comment]
yes, an old version of libcurl.so makes it (if I go back to 4.2.0).

I try after our next release to setup a test for this. It is still to complicated for further investigation,

**Comment by jakirkham** [comment]
That's a really old version of `curl`. I doubt that it will be compatible with anything at conda-forge. Why do you need that version?

**Comment by ReimarBauer** [comment]
I think I don't need it but because it has not that symbol I can't use netCDF4 for the case I access the server by its https address. Everything works if I just use http.

miniconda2/envs/stable/lib/python2.7/site-packages/netCDF4/../../.././libcurl.so.4: undefined symbol: SSLv2_client_method')

After I replaced the libcurl.so.4 by the old one (manually) then everything works as expected. Seems that the things I could broke I am not using.

libnetcdf                 4.4.1                         0  
netcdf4                   1.2.4               np111py27_0
